### ISSUE TITLE
Stops running after one training with MatplotlibDispatch

### ISSUE THREAD

**Issue by tf79** [Mri-monitoring/Mri-docs#1]
running several tasks with the server dispatch works well. However if I switch the config to dispatch = matplotlib-dispatch it performs only one task and produces this output ( I left out the most of DEBUG outputs) 

...
2015-08-12 16:51:35,715 [Thread-1    ] [DEBUG]  [CAFFE OUTPUT ] I0812 16:51:35.714720  2698 solver.cpp:343]     Test net output #1: loss = 19.9286 (\* 1 = 19.9286 loss)
2015-08-12 16:51:35,718 [MainThread  ] [DEBUG]  Processed item! Contents: iteration: 0, Attributes: {u'accuracy': 0.09}
Exception NameError: "global name 'FileNotFoundError' is not defined" in <generator object retrieve_task at 0x7ffa5c9118c0> ignored
Traceback (most recent call last):
  File "MriApp.py", line 25, in <module>
    main()
  File "MriApp.py", line 22, in main
    client.start()
  File "build/bdist.linux-x86_64/egg/mriapp/MriCaffe.py", line 69, in start
    self._run_train_directive(directive_params)
  File "build/bdist.linux-x86_64/egg/mriapp/MriCaffe.py", line 104, in _run_train_directive
    self._dispatch.train_event(item)
  File "build/bdist.linux-x86_64/egg/mri/dispatch/MatplotlibDispatch.py", line 86, in train_event
KeyError: u'name'
2015-08-12 16:51:35,782 [Thread-1    ] [DEBUG]  [CAFFE OUTPUT ] I0812 16:51:35.781991  2698 solver.cpp:214] Iteration 0, loss = 19.5206
...

At some point a window is opened and closed immediately. 

Thanks in advance! It's really a handy tool

**Comment by nharada1** [comment]
Good catch! This is indeed a bug and occurred because I'd forgotten to make some changes to the dispatch after standardizing some internal program representations. 

This should be fixed now. Please update both your Mri-App and the Mri-Client-Python to get all the changes. Let me know if this fails to fix your issue.

**Comment by tf79** [comment]
Thanks for the quick fix! Though I still have trouble to run it with matplotlib. 

Here's the output: 

...Training output...
2015-08-13 10:47:29,578 [Thread-1    ] [DEBUG]  Process finished...waiting extra for process thread to complete
2015-08-13 10:47:31,581 [Thread-1    ] [DEBUG]  Caffe thread is now marked as finished
2015-08-13 10:47:31,591 [MainThread  ] [INFO ]  Finished training! Saving output image to /home/tfiscti/Bilder/{u'base_lr':_u'1e-5',_u'weight_decay':_u'0.01'}
Exception NameError: "global name 'FileNotFoundError' is not defined" in <generator object retrieve_task at 0x7f231c00e7d0> ignored
Traceback (most recent call last):
  File "MriApp.py", line 25, in <module>
    main()
  File "MriApp.py", line 22, in main
    client.start()
  File "build/bdist.linux-x86_64/egg/mriapp/MriCaffe.py", line 69, in start
    self._run_train_directive(directive_params)
  File "build/bdist.linux-x86_64/egg/mriapp/MriCaffe.py", line 107, in _run_train_directive
    self._dispatch.train_finish()
  File "/home/tfiscti/workspace/mri/Mri-app-master/src/mri-master/mri/dispatch/MatplotlibDispatch.py", line 98, in train_finish
    plt.savefig(save_path, bbox_inches='tight')
  File "/home/tfiscti/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(_args, *_kwargs)
  File "/home/tfiscti/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(_args, *_kwargs)
  File "/home/tfiscti/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 161, in print_figure
    FigureCanvasAgg.print_figure(self, _args, *_kwargs)
  File "/home/tfiscti/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2119, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/tfiscti/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2061, in _get_output_canvas
    '%s.' % (format, ', '.join(formats)))
ValueError: Format "01'}" is not supported.
Supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff.

I guess there is no proper file format specified for saving the plot?

**Comment by tf79** [comment]
I fixed by adding ".png" in line 95 of MatplotlibDispatch to the filename. Perhaps not the nicest way to solve it. 2 other issues: 

1) Now training keeps on going but after each training a window called "Figure n" where n is corresponding to the n'th training appears. The windows always freeze and force closing them kills the training processes. 

2) However, plots are getting saved to the specified location. But I only see the accuracy graph, not the loss.

**Comment by tf79** [comment]
Sorry for another post: After all training tasks are finished all windows get closed. 

But after several windows are opened at some point ubuntu reports a problem with /usr/lib/gvfs/gvfsd-trash and one plot was not saved properly (white image). The next ones are fine again. 

Might be due to opening all the freezing windows. I tested it for only 25 training tasks and my desktop was quite crowded. Would be nice if they could be closed right away.

**Comment by nharada1** [comment]
What backend are you using for Matplotlib? 

Matplotlib backends are touchy. Some (like the one I use for testing) automatically produce PNG images. Some apparently require the file name specifically. Only some Matplotlib backends support the real-time plotting that I wanted to do, some don't create a window at all, etc etc.

This is definitely an oversight on my part to not effectively deal with all the variance of backends. If you let me know what one you use I can try and figure out what are bugs in my code and what are limitations of the backend.

Run this to get your backend

```
>>> import matplotlib.pyplot as plt
>>> plt.get_backend()
```

**Comment by tf79** [comment]
Thank you very much for your help! I really appreciate it! The tool is really nice and saves me a lot of time! 

About not displaying the loss: I was wrong, sorry. It get's displayed but for many of my trainings it's above 1 which is the limit for the y-axis. 

my backend is: u'Qt4Agg'

I just started a a task session with a couple thousand trainings. I gonna let you know how it worked out by tomorrow. So far no ubuntu crashes. For this kind of task automatic closing the windows would be nice as well as getting the top ten trainings results or storing the results in some easy format to do some statistics on it. I have no clue about python if something like this is even possible. 

I have no clue how to get to work with the local web server. No chance of using the Heroku solution, because I can't get through the network proxy. But might be a good alternative at some point, because I would need to make some small changes in the plots anyway (units, title). With the number of different parameters you easily get in trouble with the max file length and the title in the plots does not look readable using extremely short parameter names. 

If you are interested in some other suggestions just let me know. I might have some more ideas. Unfortunately I can't be much of help with programming, because I have never used python before. Sorry!

**Comment by nharada1** [comment]
Alright, so here's what I did. I fixed some of the issues straight up. I'm pretty sure only some systems defaulted to PNG, for example, so now I explicitly set that as default. 

I also changed how Matplotlib deals with plots. Previously the strange behavior you were seeing was actually a side-effect of the Python garbage collector. Now you have two options: a new window per task that closes at the end of training, or no windows. In theory we could probably have many windows open during training but unless that's a feature many people want let's table it since that will require an architecture change.

Here are the actual commit notes:
- Removed the default locked y-axis, so y-axis now scales automatically
- Set default file output type to PNG when saving images
- Added config option 'show_windows' to for plots during training
- Made default the option to now show windows
- Multiple windows will now not show at once

For the local web server, it's a bit of a pain. You'll need a MongoDB database if you can't access Heroku at all. You'll also need a system that can run NodeJS. If you have those two things you should be able to run the server.

Please feel free to leave more bug reports and suggestions (preferably in a different thread). Without other people helping bug-test I'd just discover these bugs the hard way!

**Comment by tf79** [comment]
Thanks for the fixes! 
- saving images now works.
- Training does not stop anymore
